spring:
  application:
    name: tasklist
    version: 1.0.0-SNAPSHOT
  profiles:
    active: ${PROFILE:dev}
  jackson:
    serialization:
      write-dates-as-timestamps: false
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${DS_URL:localhost}:${DS_PORT:5432}/${DS_DATABASE:tasklist}
    password: ${DS_PASS:postgres}
    username: ${DS_USER:postgres}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: 'true'
    hibernate:
      ddl-auto: update
    generate-ddl: 'false'
jwt:
  secret: ${JWT_SECRET:3c4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3d4e}
  expiration: 86400000
  refresh-expiration: 604800000
management:
  endpoints:
    web:
      exposure:
        include: health,info
server:
  port: ${PORT:8080}
  forward-headers-strategy: framework
logging:
  level:
    root: info
    org.springframework.web: info
    br.com.jtech.tasklist: debug
  file:
    name: ./logs/${spring.application.name}.log
springdoc:
  api-docs:
    groups:
      enabled: 'true'
    path: /doc/tasklist/v3/api-documents
  swagger-ui:
    enabled: 'true'
    path: /doc/tasklist/v1/api.html
api:
  version: v1
  description: Description here
  url:
    homologation: http://${HOMOLOGATION_SERVER:172.30.1.24}:${HOMOLOGATION_PORT:8081}
    production: ${PRODUCTION_URI:http://${spring.application.name}.jtech.com.br}
